### ISSUE TITLE
Problema ao autorizar uma aplicação usando o SetJwksOptions

### ISSUE THREAD

**Issue by byelmendes** [NetDevPack/Security.JwtExtensions#2]
"NetDevPack.Security.JwtExtensions" Version="5.0.1"

Encontrei um problema ao validator o token JWT numa aplicação client.

Em um ISecurityTokenValidator implementado é feito a validação do token pelo System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler. Ao final dessa validação se tudo estiver correto o handler retorna um System.Security.Claims.ClaimsPrincipal. Nesse momento pelo comportamento do framework eu tenho um System.Security.Principal.IIdentity no contexto da requisição.

![image](https://user-images.githubusercontent.com/10376877/119582031-306d1300-bd9a-11eb-826f-2bc8ed937225.png)

Agora é que vem o problema. Num IAsyncAuthorizationFilter implementado quando faço a verificação Identity.IsAuthenticated o retorno é false, pois o contexto está sem uma identidade.

![image](https://user-images.githubusercontent.com/10376877/119582080-50043b80-bd9a-11eb-8976-54ca09ac581d.png)

Esse problema acontece dentro do JwksRetriever no médoto GetAsync.

![image](https://user-images.githubusercontent.com/10376877/119582228-99ed2180-bd9a-11eb-9f3e-80617062ebd1.png)

Com o ConfigureAwait como false a thread que originou o Identity não será a mesma dentro do filtro e consequentemente dentro do contexto da minha aplicação.

**Comment by brunohbrito** [comment]
Oi @byelmendes,

A issue foi fechada. Houve algum desdobramento ?

**Comment by byelmendes** [comment]
Oi @brunohbrito,

Eu ajustei no código e mesmo assim não houve mudança de comportamento. Acredito que exista algo além dessa minha análise, inclusive alguma má implementação da minha parte.

Por isso resolvi fechar a issue. O que mais me intriga é que quando removo a linha abaixo funciona corretamente.

`options.SetJwksOptions(new JwkOptions($"{ authorityOptions.Endpoint }/jwks"));`

Agradeço pelo retorno e desculpe pela issue aberta!
