### ISSUE TITLE
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Exception

### ISSUE THREAD

**Issue by josematheus10** [NetDevPack/Security.JwtExtensions#3]
Pessoal eu estou com esse erro aleatório baixo, será que meu JKS tem algum dado inválido? 

    [2022-06-24 16:08:31.2058]: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Exception occurred while processing message. System.Threading.Tasks.TaskCanceledException: A task was canceled.
    [ at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)]:
    [ at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()]:
    [ at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()]:
    [ at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()]:
    [ at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)]:
    [ at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)]:
    [ at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)]:
    [ at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()]:

**Comment by brunobritodev** [comment]
Sim, talvez o endpoint jwks esteja com algum problema
